version: "3.8"
services:
  app:
    build: ./infra/php
    volumes:
      - ./backend:/work

  # web
  web:
    image: nginx:1.18-alpine
    depends_on:
      - app
    ports: 
      - "10080:80"
    volumes: 
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work
  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store: